apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-demo-deploy
spec:
  replicas: 1
  template:
    metadata:
        labels:
          app: springboot-demo
    spec:
      containers:
      - name: springboot-demo
        image: hub.navinfo.com/devops/springboot-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-demo-svc
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30001
  selector:
    app: springboot-demo